### ISSUE TITLE
Multiple users on same sheet

### ISSUE THREAD

**Issue by ZyborgRSA** [Blacksmoke16/GESI#14]
Having issues with multiple users on the same sheet.

I can auth as many characters/accounts as I want, and they all run fine, however if someone else (who isn't the owner of the sheet) attempts to do the same, it never auths, even though it says it has successfully authed. As I said, if he copies the sheet, reauths, it runs fine.

**Comment by Blacksmoke16** [comment]
I think the issue of this is either the Google OAuth library or some service i am caching the data in is scoped to current user, so other users do not have access to the data stored (i.e. the auth token).  

I am going to assign this for version 4.0.0 which will rework the auth system so that i have more control.

**Comment by Blacksmoke16** [comment]
Fixed in 4.0.0
