### ISSUE TITLE
Refresh token is missing

### ISSUE THREAD

**Issue by Errious** [Blacksmoke16/GESI#21]
Hi,

any idea why i get for any function error 400 
https://login.eveonline.com/oauth/token. 
{"error":"invalid_request","error_description":"Refresh token is missing."}.

???

Best Regards

**Comment by Blacksmoke16** [comment]
There are some issues with documentProperties (where I am storing character data atm) I have discovered recently.  This will be fixed in version 5 sometime early next week.  It seems for whatever reason, data stored in there is getting deleted. 

A few things to check until version 5 is out:
1. Make sure the character name you are using in either the `CHARACTERS` array or in the `name` param of a function matches exactly the name of your character you authed.  
2. Make sure you authed that character.
3. Look in the documentProperties object to see if other data is in there.

```
    function test() {
        Logger.log(DOCUMENT_PROPERTIES.getProperties());
    }
```

Add that function to GESI.gs and run it in the script editor, then check the logs.

**Comment by Errious** [comment]
Everytime i try to auth the character i try to log in and when i have to enter the google authenticator i get the answer the Login failed. Possible reasons can be: Your login session has expired. Please try again.

**Comment by Blacksmoke16** [comment]
I had the issuer too!  Was super annoying.  Solution for that i found is remove some scopes you do not use.  The URL is too long and causes issues from what i figure.

**Comment by Blacksmoke16** [comment]
Fixec in #22
