### ISSUE TITLE
Issues Having friends use my skill check sheet

### ISSUE THREAD

**Issue by jlmorrison3** [Blacksmoke16/GESI#48]
When I enter any of my accounts into the authorization portal it works fine. But my friends get this error after selecting their characters: You are trying to edit a protected cell or object. Please contact the spreadsheet owner to remove protection if you need to edit. (line 257, file "gesi", project "GESI")
Is there a way to allow them to use my sheet I shared with them without need them to make their own copies? (I assume the making their own private copy may fix the issue)

**Comment by Blacksmoke16** [comment]
My default the `Auth Data` sheet is limited to only the sheet owner for security reasons, since that sheet contains sensitive data that you wouldn't want people to see.  However, if you trust your friends to not use your tokens for malicious purposes, you can just remove the protection on that sheet.

**Comment by jlmorrison3** [comment]
Where do I get access to that sheet at? Sorry I've just kind of started to get into using the add on so don't know how to navigate it well

**Comment by Blacksmoke16** [comment]
Np.  Just know anyone with edit access to your sheet basically has full access to your ESI data.  You would also have access to other authed characters on your sheet.  Safest way would you develop a sheet, and they just make a copy and auth their chars.
