### ISSUE TITLE
Invalid_scope

### ISSUE THREAD

**Issue by GhostShell77** [Blacksmoke16/GESI#5]
Hi ! 
I try to use your script, but i have an issue !
i follow all the step and all is ok, but,  when i click on the link in the side panel, the new page show this code : 

> {"error":"invalid_scope","error_description":"The requested scopes either don't exist, or are not valid for this client"}

Thank you.

**Comment by Blacksmoke16** [comment]
Did you go back into your dev application and add the three new scopes?

esi-industry.read_character_jobs.v1
esi-characters.read_blueprints.v1
esi-markets.read_character_orders.v1

**Comment by GhostShell77** [comment]
yes, i selected all of this : 

- esi-calendar.respond_calendar_events.v1
- esi-calendar.read_calendar_events.v1
- esi-location.read_location.v1
- esi-location.read_ship_type.v1
- esi-skills.read_skills.v1
- esi-wallet.read_character_wallet.v1
- esi-search.search_structures.v1
- esi-clones.read_clones.v1
- esi-universe.read_structures.v1
- esi-assets.read_assets.v1
- esi-markets.structure_markets.v1
- esi-corporations.read_structures.v1
- esi-corporations.write_structures.v1
- esi-characters.read_loyalty.v1
- esi-industry.read_character_jobs.v1
- esi-markets.read_character_orders.v1
- esi-characters.read_blueprints.v1

**Comment by Blacksmoke16** [comment]
Select all of the ESI scopes.  This issue is because you do not have a scope set in your dev app that is used in GESI.  

You can see all the scopes used in GESI on line 199 where it says .setScope('.....');  But, again, it would just be easier to add them all so when I add another endpoint you do not have to go back and add the new one every time.

Any other problems, open a new issue.

**Comment by GhostShell77** [comment]
Thank you !
I didn't see that they had to be defined !
Sorry for the disruption.
