### ISSUE TITLE
Addon not verified by Google

### ISSUE THREAD

**Issue by intrapt** [Blacksmoke16/GESI#70]
When installing a script needed for GESI after installing the addon, the following message is displayed instead of allowing users to sign in: "Sign in with Google temporarily disabled for this app
This app has not yet been verified by Google in order to use Google Sign in."

Looking at the reviews of GESI, it looks like Google changed their minds after previously resolving this issue on March 7th.

**Comment by Blacksmoke16** [comment]
Are you sure?  I'd just try it again.

**Comment by intrapt** [comment]
I tried multiple times. Same error all the time

**Comment by intrapt** [comment]
Works now :D

**Comment by Blacksmoke16** [comment]
:+1:, I didn't do anything so :shrug:.

**Comment by jw2476** [comment]
I'm getting this issue...

**Comment by Blacksmoke16** [comment]
If you're getting this right after installing, it's probably https://issuetracker.google.com/issues/155977975.

I'd read thru the first post to confirm that's what you're running into.  If it is then there isn't anything I can do as its a Google issue.  Otherwise let me know and I can reopen this issue.
